walkonwater:
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 80
    unhealthy_threshold: 3
    initializing_timeout: 60000
    interval: 2000
    strategy: recreate
    reinitializing_timeout: 60000

walkonwater-server-lb:
    lb_config:
      config: |-
        global
          nbproc 8
        defaults
          mode http
          maxconn 500000
          balance leastconn 
          timeout connect 5s		
          timeout client 60s
          timeout server 60s
          timeout http-request 10s
        backend walkonwater
          option http-buffer-request
      port_rules:
      - backend_name: walkonwater
        hostname: ''
        path: /
        protocol: http
        service: walkonwater
        source_port: 80
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
