# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20171006_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.RemoveField(
            model_name='feed',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='type',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
